project:
  type: website
  output-dir: docs

website:
  title: "Jose De Leon"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: tutorial.qmd
        text: Prophet Tutorial
